// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// idDub
NumericVector idDub(int i, NumericVector inputlat, NumericVector inputlon, NumericMatrix inputdata, NumericVector outputlat, NumericVector outputlon, NumericVector landmask);
RcppExport SEXP holmberg_idDub(SEXP iSEXP, SEXP inputlatSEXP, SEXP inputlonSEXP, SEXP inputdataSEXP, SEXP outputlatSEXP, SEXP outputlonSEXP, SEXP landmaskSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type inputlat(inputlatSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type inputlon(inputlonSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type inputdata(inputdataSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type outputlat(outputlatSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type outputlon(outputlonSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type landmask(landmaskSEXP);
    __result = Rcpp::wrap(idDub(i, inputlat, inputlon, inputdata, outputlat, outputlon, landmask));
    return __result;
END_RCPP
}
// idDub_allRows
NumericMatrix idDub_allRows(NumericVector inputlat, NumericVector inputlon, NumericMatrix inputdata, NumericVector outputlat, NumericVector outputlon, NumericVector landmask);
RcppExport SEXP holmberg_idDub_allRows(SEXP inputlatSEXP, SEXP inputlonSEXP, SEXP inputdataSEXP, SEXP outputlatSEXP, SEXP outputlonSEXP, SEXP landmaskSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type inputlat(inputlatSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type inputlon(inputlonSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type inputdata(inputdataSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type outputlat(outputlatSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type outputlon(outputlonSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type landmask(landmaskSEXP);
    __result = Rcpp::wrap(idDub_allRows(inputlat, inputlon, inputdata, outputlat, outputlon, landmask));
    return __result;
END_RCPP
}
// invDistWInt
NumericVector invDistWInt(NumericVector inputlat, NumericVector inputlon, NumericVector inputdata, NumericVector outputlat, NumericVector outputlon);
RcppExport SEXP holmberg_invDistWInt(SEXP inputlatSEXP, SEXP inputlonSEXP, SEXP inputdataSEXP, SEXP outputlatSEXP, SEXP outputlonSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type inputlat(inputlatSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type inputlon(inputlonSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type inputdata(inputdataSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type outputlat(outputlatSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type outputlon(outputlonSEXP);
    __result = Rcpp::wrap(invDistWInt(inputlat, inputlon, inputdata, outputlat, outputlon));
    return __result;
END_RCPP
}
