# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

idDub <- function(i, inputlat, inputlon, inputdata, outputlat, outputlon) {
    .Call('holmberg_idDub', PACKAGE = 'holmberg', i, inputlat, inputlon, inputdata, outputlat, outputlon)
}

invDistWInt <- function(inputlat, inputlon, inputdata, outputlat, outputlon) {
    .Call('holmberg_invDistWInt', PACKAGE = 'holmberg', inputlat, inputlon, inputdata, outputlat, outputlon)
}

