# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' calculate data based on inverse distance weighted interpolation
#'
#'
#' @param inputlat latitudes of input data
#' @param inputlon longitudes of input data
#' @param inputdata input data
#' @param outputlat latitudes of output data
#' @param outputlon longitudes of output data
#' @param landmask aligned data for masking
#' 
#' @keywords inverse distance weighted average
#' @export
#'
idDub_allRows <- function(inputlat, inputlon, inputdata, outputlat, outputlon, landmask) {
    .Call('holmberg_idDub_allRows', PACKAGE = 'holmberg', inputlat, inputlon, inputdata, outputlat, outputlon, landmask)
}

#' calculate data based on inverse distance weighted interpolation
#'
#'
#' @param i row number to analyse
#' @param inputlat latitudes of input data
#' @param inputlon longitudes of input data
#' @param inputdata input data
#' @param outputlat latitudes of output data
#' @param outputlon longitudes of output data
#' @param landmask aligned data for masking
#' 
#' @keywords inverse distance weighted average
#' @export
#'
idDub <- function(i, inputlat, inputlon, inputdata, outputlat, outputlon, landmask) {
    .Call('holmberg_idDub', PACKAGE = 'holmberg', i, inputlat, inputlon, inputdata, outputlat, outputlon, landmask)
}

#' interpolate missing y values to fill a given x series
#'
#'
#' @param x_in input x series
#' @param y_in input variable series
#' @param x_out output x series
#' 
#' @keywords interpolate
#' @export
#'
interpolate <- function(x_in, y_in, x_out) {
    .Call('holmberg_interpolate', PACKAGE = 'holmberg', x_in, y_in, x_out)
}

invDistWInt <- function(inputlat, inputlon, inputdata, outputlat, outputlon) {
    .Call('holmberg_invDistWInt', PACKAGE = 'holmberg', inputlat, inputlon, inputdata, outputlat, outputlon)
}

